### ISSUE TITLE
Stateless parser

### ISSUE THREAD

**Issue by mathewrapid** [Jalle19/certificate-parser#1]
Would it be an idea to change the parser to a stateless one?

Now if you now need to e.g. parse x amount of domains, then you need to create x instances of providers _and_ x instances of parsers.

**Comment by Jalle19** [comment]
Would it be okay to just add a `setProvider()` method? That way the interface/major version wouldn't have to be changed.

**Comment by mathewrapid** [comment]
Then you would change the state of the parser in these cases. Imho. not a clean approach.

Perhaps next _major_ version update?

**Comment by Jalle19** [comment]
IMO it's a pretty standard approach, i.e. inject dependencies via the constructor but allow dynamic re-injection through setters. We'll see.
